property_setter = {
	"dt": "Property Setter",
	"filters": [["name", "in", ["Journal Entry-user_remark-print_hide",
								"Journal Entry-total_debit-in_list_view",
								"Journal Entry-total_debit-print_hide",
								"Journal Entry-total_credit-print_hide",
								"Journal Entry-total_amount-in_list_view",
								"Journal Entry-total_amount-print_hide",
								"Journal Entry-total_amount-bold",
								"Journal Entry-remark-in_global_search",
								"Journal Entry-pay_to_recd_from-allow_on_submit",
								"Journal Entry-read_only_onload",
								"Address-city-reqd",
								"Address-email_id-hidden",
								"Address-phone-hidden",
								"Address-read_only_onload",
								"Address-fax-read_only",
								"Address-fax-hidden",
								"Warehouse-sort_order",
								"Warehouse-read_only_onload",
								"Stock Reconciliation-read_only_onload",
								"Stock Reconciliation-expense_account-depends_on",
								"Reconciliation-expense_account-read_only",
								"Stock Reconciliation-expense_account-in_standard_filter",
								"Stock Entry Detail-read_only_onload",
								"Stock Entry-purpose-default",
								"Stock Entry-to_warehouse-in_list_view",
								"Stock Entry-to_warehouse-hidden",
								"Stock Entry-from_warehouse-in_list_view",
								"Stock Entry-supplier-in_list_view",
								"Stock Entry-project-hidden",
								"Stock Entry-search_fields",
								"Stock Entry-title_field",
								"Stock Entry-read_only_onload"]]]
}
