custom_field = {
	"dt":"Custom Field", 
		"filters": [
			["name", "in", [
				"Stock Entry Detail-rejection_qty",
				"Stock Entry Detail-po_rate",
				"Stock Entry Detail-po_amount",
				"Stock Entry-total_p_amount",
				"Purchase Invoice-section_break_40",
				"Purchase Invoice-form_types",
				"Sales Invoice Item-customer_po_date",
				"Sales Invoice-customer_purchase_order",
				"Sales Invoice-customer_purchase_order_date",
				"Sales Invoice-mode_of_dispatch",
				"Sales Invoice-total_qty","Stock Reconciliation-section_break_0",
				"Stock Reconciliation-remarks",
				"Delivery Note-section_break_0",
				"Delivery Note-remarks",
				"Purchase Order-remarks",
				"Purchase Order-section_break_0",
				"Item-process_no",
				"Delivery Note-mode_of_dispatch",
				"Delivery Note Item-customer_po_date",
				"Delivery Note Item-customer_purchase_order",
				"Sales Order Item-customer_purchase_order",
				"Sales Order Item-customer_po_date",
				"Purchase Receipt-supplier_invoice_no",
				"Purchase Order-format_no",
				"Purchase Invoice-section_break_0",
				"Purchase Order Item-gst_hsn_code",
				"Sales Invoice Item-gst_hsn_code",
				"Purchase Receipt Item-gst_hsn_code",
				"Address-gst_state_number",
				"Address-gst_state",
				"Address-gstin",
				"Sales Order Item-gst_hsn_code",
				"Sales Invoice-shipping_bill_date",
				"Sales Invoice-shipping_bill_number",
				"Sales Invoice-port_code",
				"Sales Invoice-company_gstin",
				"Sales Invoice-place_of_supply",
				"Sales Invoice-customer_gstin",
				"Sales Invoice-billing_address_gstin",
				"Sales Invoice-reason_for_issuing_document",
				"Sales Invoice-column_break_0",
				"Sales Invoice-ecommerce_gstin",
				"Sales Invoice-export_type",
				"Sales Invoice-invoice_type",
				"Sales Invoice-reverse_charge",
				"Sales Invoice-invoice_copy",
				"Sales Invoice-section_break_0",
				"Delivery Note-shipping_bill_date",
				"Delivery Note-shipping_bill_number",
				"Delivery Note-port_code",
				"Delivery Note-company_gstin",
				"Delivery Note-place_of_supply",
				"Delivery Note-customer_gstin",
				"Delivery Note-billing_address_gstin",
				"Purchase Invoice-itc_cess_amount",
				"Purchase Invoice-itc_state_tax",
				"Purchase Invoice-itc_central_tax",
				"Purchase Invoice-itc_integrated_tax",
				"Purchase Invoice-eligibility_for_itc",
				"Purchase Invoice-place_of_supply",
				"Purchase Invoice-company_gstin",
				"Purchase Invoice-supplier_gstin",
				"Purchase Invoice-reason_for_issuing_document",
				"Purchase Invoice-column_break_0",
				"Purchase Invoice-ecommerce_gstin",
				"Purchase Invoice-export_type",
				"Purchase Invoice-invoice_type",
				"Purchase Invoice-reverse_charge",
				"Purchase Invoice-invoice_copy",
				"Quotation Item-gst_hsn_code",
				"Purchase Invoice Item-gst_hsn_code",
				"Delivery Note Item-gst_hsn_code",
				"Item-gst_hsn_code",
				"Supplier Quotation Item-gst_hsn_code",
				"Purchase Invoice-form_types"
			]
		]
	]
}

