property_setter = {
	"dt": "Property Setter",
	"filters": [["name", "in", ["Journal Entry-user_remark-print_hide",
								"Journal Entry-total_debit-in_list_view",
								"Journal Entry-total_debit-print_hide",
								"Journal Entry-total_credit-print_hide",
								"Journal Entry-total_amount-in_list_view",
								"Journal Entry-total_amount-print_hide",
								"Journal Entry-total_amount-bold",
								"Journal Entry-remark-in_global_search",
								"Journal Entry-pay_to_recd_from-allow_on_submit",
								"Journal Entry-read_only_onload",
								"Address-city-reqd",
								"Address-email_id-hidden",
								"Address-phone-hidden",
								"Address-read_only_onload",
								"Address-fax-read_only",
								"Address-fax-hidden",
								"Warehouse-sort_order",
								"Warehouse-read_only_onload",
								"Stock Reconciliation-read_only_onload",
								"Stock Reconciliation-expense_account-depends_on",
								"Reconciliation-expense_account-read_only",
								"Stock Reconciliation-expense_account-in_standard_filter",
								"Stock Entry Detail-read_only_onload",
								"Stock Entry-purpose-default",
								"Stock Entry-to_warehouse-in_list_view",
								"Stock Entry-to_warehouse-hidden",
								"Stock Entry-from_warehouse-in_list_view",
								"Stock Entry-supplier-in_list_view",
								"Stock Entry-project-hidden",
								"Stock Entry-search_fields",
								"Stock Entry-title_field",
								"Stock Entry-read_only_onload",
								"Purchase Receipt Item-qty-in_list_view",
								"Purchase Receipt Item-price_list_rate-fieldtype",
								"Purchase Receipt Item-base_price_list_rate-fieldtype",
								"Purchase Receipt Item-rate-fieldtype",
								"Purchase Receipt Item-amount-in_list_view",
								"Purchase Receipt Item-read_only_onload",
								"Purchase Receipt Item-base_rate-fieldtype",
								"Purchase Receipt-taxes_and_charges-hidden",
								"Purchase Receipt-taxes-hidden",
								"Purchase Receipt-remarks-reqd",
								"Purchase Receipt-read_only_onload",
								"Item-income_account-depends_on",
								"Item-income_account-default",
								"Item-read_only_onload",
								"Delivery Note Item-read_only_onload",
								"Delivery Note Item-warehouse-default",
								"Delivery Note-posting_time-description",
								"Delivery Note-posting_time-print_hide",
								"Delivery Note-taxes_section-hidden",
								"Delivery Note-taxes_and_charges-hidden",
								"Delivery Note-taxes-hidden",
								"Delivery Note-project-hidden",
								"Delivery Note-sales_team_section_break-hidden",
								"Delivery Note-read_only_onload",
								"Delivery Note-section_break1-hidden",
								"Serial No-description-in_standard_filter",
								"Serial No-purchase_date-in_standard_filter",
								"Serial No-supplier-in_standard_filter",
								"Serial No-supplier_name-in_standard_filter",
								"Serial No-supplier_name-bold",
								"Serial No-delivery_document_type-in_standard_filter",
								"Serial No-delivery_document_no-in_standard_filter",
								"Serial No-customer-in_standard_filter",
								"Serial No-customer_name-bold",
								"Serial No-customer_name-in_standard_filter",
								"Serial No-maintenance_status-in_standard_filter",
								"Serial No-warranty_expiry_date-in_standard_filter",
								"Serial No-amc_expiry_date-in_standard_filter",
								"Serial No-company-in_standard_filter",
								"Serial No-read_only_onload"]]]
}
