property_setter = {
	"dt": "Property Setter",
	"filters": [["name", "in", ['Serial No-company-in_standard_filter',
								'Serial No-delivery_document_type-in_standard_filter',
								'Sales Invoice Item-customer_item_code-label',
								'Serial No-description-in_standard_filter',
								'Sales Invoice-taxes_and_charges-reqd',
								'Sales Order-taxes-hidden',
								'Delivery Note Item-warehouse-default',
								'Stock Entry-purpose-default',
								'Purchase Receipt-taxes-hidden',
								'Serial No-customer_name-bold',
								'Stock Entry-to_warehouse-hidden',
								'Delivery Note-sales_team_section_break-hidden',
								'Serial No-delivery_document_no-in_standard_filter',
								'Journal Entry-total_amount-bold',
								'Purchase Order Item-rate-fieldtype',
								'Address-fax-read_only',
								'Purchase Receipt-taxes_and_charges-hidden',
								'Currency Exchange-sort_order',
								'Serial No-warranty_expiry_date-in_standard_filter',
								'Purchase Receipt Item-price_list_rate-fieldtype',
								'Item-income_account-depends_on',
								'Journal Entry-total_debit-in_list_view',
								'Delivery Note-posting_time-description',
								'Delivery Note-taxes_and_charges-hidden',
								'Journal Entry-total_credit-print_hide',
								'Journal Entry-total_debit-print_hide',
								'Stock Reconciliation-expense_account-in_standard_filter',
								'Journal Entry Account-exchange_rate-print_hide',
								'Delivery Note-section_break1-hidden',
								'BOM-rm_cost_as_per-reqd',
								'Journal Entry-remark-in_global_search',
								'Warehouse-sort_order',
								'Journal Entry Account-sort_order',
								'Purchase Receipt Item-base_price_list_rate-fieldtype',
								'Purchase Receipt Item-amount-in_list_view',
								'Journal Entry-pay_to_recd_from-allow_on_submit',
								'Serial No-purchase_date-in_standard_filter',
								'Stock Entry-to_warehouse-in_list_view',
								'Serial No-amc_expiry_date-in_standard_filter',
								'Sales Invoice Item-item_code-label',
								'BOM-operations_section-read_only',
								'BOM-rm_cost_as_per-options',
								'Serial No-supplier_name-in_standard_filter',
								'Address-city-reqd',
								'Journal Entry-user_remark-print_hide',
								'Purchase Receipt-remarks-reqd',
								'Delivery Note-posting_time-print_hide',
								'Delivery Note-taxes-hidden',
								'Delivery Note-taxes_section-hidden',
								'Company-abbr-in_list_view',
								'Delivery Note-project-hidden',
								'BOM Operation-sort_order',
								'Purchase Order Item-price_list_rate-fieldtype',
								'ToDo-sort_order',
								'Journal Entry Account-account_currency-print_hide',
								'Sales Invoice-default_print_format',
								'Reconciliation-expense_account-read_only',
								'Address-phone-hidden',
								'Serial No-customer-in_standard_filter',
								'Customer-tax_id-read_only',
								'Journal Entry-total_amount-print_hide',
								'Item-income_account-default',
								'Purchase Receipt Item-base_rate-fieldtype',
								'Purchase Order Item-amount-fieldtype',
								'Serial No-supplier_name-bold',
								'Address-fax-hidden',
								'Purchase Receipt Item-rate-fieldtype',
								'BOM-operations-read_only',
								'Stock Entry-supplier-in_list_view',
								'Purchase Taxes and Charges Template-sort_order',
								'Stock Entry-from_warehouse-in_list_view',
								'Stock Entry-title_field',
								'Stock Entry-search_fields',
								'Serial No-supplier-in_standard_filter',
								'Stock Reconciliation-expense_account-depends_on',
								'BOM Item-scrap-read_only',
								'Address-email_id-hidden',
								'Serial No-customer_name-in_standard_filter',
								'Sales Taxes and Charges-sort_order',
								'Serial No-maintenance_status-in_standard_filter',
								'Purchase Receipt Item-qty-in_list_view',
								'Journal Entry-total_amount-in_list_view',
								'Stock Entry-project-hidden']
				]]

}